### ISSUE TITLE
How to show A dialog if the "Version Is Up to Date"

### ISSUE THREAD

**Issue by GOPALAKRISHNAREDDY** [winsontan520/Android-WVersionManager#11]
everything is fine, and everything is working perfectly for me, but how can we put the dialog if the version is uptodate,
currently it is not displaying any dialog if the version is uptodate.
so can u say how can i set that dialog?

"Your Version Is UpToDate".

**Comment by winsontan520** [comment]
Currently it will only show if any update available.
For your case, you might need handle yourself in setOnReceiveListener
eg:
versionManager.setOnReceiveListener(new OnReceiveListener() {
@Override
public boolean onReceive(int status, String result) {
// compare current app version code with result then show dialog
accordingly here

return false;
                // return true if you want to use library's default logic &
dialog
}
});

On Thu, Feb 9, 2017 at 8:14 PM, GOPALAKRISHNAREDDY <notifications@github.com

**Comment by winsontan520** [comment]
versionManager.setOnReceiveListener(new OnReceiveListener() {
@Override
public boolean onReceive(int status, String result) {
if(isLatestVersion){
showYourOwnDialog();
return false;
}else{
          // show default dialog as usual
          return true;
        }
);

**Comment by GOPALAKRISHNAREDDY** [comment]
I have already fixed that, now it is showing dialog for uptodate version,
Thanks for u r code
